# 示例配置文件

# 用户信息
[user]
# 你的账号
id = "demo_id"
# 你的密码
pwd = "demo_pwd"
# 接收邮件提醒的邮箱
# 如果想使用此功能请取消下行注释
# email = "asdasd@qq.com"

# 重试次数
# 推荐为3，因为次数变多也几乎没用
# 如果想修改，请取消下行注释并修改
# retry = 3

# 邮件提醒设置
# 如果 [user] 中填写了邮箱推荐完善此设置
[email]
# 邮箱账号
user = "email_user@xxx.com"
# smtp授权码
# 注意不是登录密码
# 获取方式请参考: https://laowangblog.com/qq-mail-smtp-service.html
pwd = "password"

# 发送人
# 默认："tjuptatt_bot"
# sender = "sender"

# 端口，默认465
# port = 465

# smtp host 默认 QQ
# host = "smtp.qq.com"

# TOP10 签到设置
# 仅在TOP10模式下使用
[time]
# TOP10 签到的时间点
# 如果开启TOP10模式，则会选择最近的一次签到时间点
# 格式：时 分 秒 纳秒
# 注意：不要在这里考虑延迟, 建议保持默认不要修改
# 其中午夜(0,0,0,0)为第二天的0点
top_ten_points = [
    [0, 0, 0, 0], [6, 0, 0, 0], [7, 0, 0, 0], [8, 0, 0, 0], 
    [12, 0, 0, 0], [18, 0, 0, 0], [20, 0, 0, 0], [22, 0, 0, 0]
]

# 延迟设置
# 格式：秒 纳秒
# 1s = 10^3ms, 1ms = 10^6ns
# 只能写整数 纳秒范围为：[0, 10^9)

# 网络延迟，在TOP10模式使用
# 建议设置范围 0~20ms
delay = [0, 20000000]

# 普通时间点使用，可以稍微比 delay 大一点
# 建议范围：20~50ms
post_delay = [0, 40000000]

# 登录所需要的时间
# 建议3s
login_delay = [3, 0]

# 获取答案所需要的时间
# 建议3s
answer_delay = [3, 0]
